### DISCUSSION TITLE
How can I customize the summary of list pages ?

### DISCUSSION THREAD

**Discussion by ghost** [willfaught/paige#59] [Q&A] [answered]
There are two pages in the [customization menu](https://github.com/willfaught/paige/tree/master/exampleSite/content/customization) - `show.md` and `style.md`.

The `_index.md` file of this menu is configured in a way which shows the date header, title, description, keywords, the text above `<!--more-->`, series, etc. of both these pages.

Is it possible to customize 

```
---
...
...
paige:
  style:
---
```

in `_index.md` such that only the title, author, and keywords are displayed for `show.md` and `style.md` in the [customization page](https://willfaught.com/paige/customization/)?

**Comment by willfaught** [comment]
Page parameters aren't inherited between parent and child pages. If you look at the front matter for _index.md, show.md, and style.md, you can see that they each specify a paige.style value:

```yaml
paige:
  style: |
    #paige-authors,
    #paige-credit,
    #paige-date,
    #paige-keywords,
    #paige-reading-time,
    #paige-series,
    #paige-toc,
    .paige-authors,
    .paige-date,
    .paige-date-header,
    .paige-keywords,
    .paige-reading-time,
    .paige-series,
    .paige-summary {
        display: block;
    }
```

By default, all page content is displayed, so if you want _index.md to only show the title, author, and keywords, you would style everything else to not be displayed:

```yaml
paige:
  style: |
    /* #paige-authors, */
    #paige-credit,
    #paige-date,
    /* #paige-keywords, */
    #paige-reading-time,
    #paige-series,
    #paige-toc,
    /* .paige-authors, */
    .paige-date,
    .paige-date-header,
    /* .paige-keywords, */
    .paige-reading-time,
    .paige-series,
    .paige-summary {
        display: none; /* none, not block */
    }
```
