### DISCUSSION TITLE
Bootstrap Icons in menu

### DISCUSSION THREAD

**Discussion by scluff** [willfaught/paige#83] [Q&A] [answered]
Is is possible to use Bootstrap Icons inside of menu entries? I have seen some examples using the pre property in menu entries to add an icon, but not having much luck.

```
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 10
pre = '<i class="bi bi-house"></i>'
```

**Comment by willfaught** [comment, marked as answer]
v0.91.0 renders menu names as Markdown, so this should now work:

```toml
[[languages.en.menu.main]]
name = '<i class="bi bi-house"></i> Home'
url = "/"
weight = 10
```
