### ISSUE TITLE
social links are not shown

### ISSUE THREAD

**Issue by goern** [willfaught/paige#17]
follow up of https://github.com/willfaught/paige/discussions/12#discussioncomment-5411805

> By the way, where is  coming from?

I dont know... then I found https://discourse.gohugo.io/t/raw-html-omitted-in-templates/43375/8

and added 
```
markup:
  goldmark:
    renderer:
      unsafe: true
``` 

to `config.yaml`, now it works. I was not aware that I need to have that set.

/kind documentation
