### ISSUE TITLE
Feature Request: Improve differentiation between categories and tags in list layout

### ISSUE THREAD

**Issue by allocgator** [willfaught/paige#88]
Take [this page](https://willfaught.com/paige/customizations/) for instance, where "Show Data" and "Style Data" are listed. 

The page "Show Data" has categories `"customization", "paige"` and tags `"show", "singles"` (from this [source](https://raw.githubusercontent.com/willfaught/paige/master/exampleSite/content/customizations/show.md)) and page "Style Data" has categories `"customization", "paige"` and tags `"singles", "style"` (from this [source](https://raw.githubusercontent.com/willfaught/paige/master/exampleSite/content/customizations/style.md)).

When these pages are listed under [customizations](willfaught.com/paige/customizations/), it's unclear what the categories and tags are respectively.

In cases where this list is big (30+ pages), identifying them is tougher. 

Requesting a feature to differentiate between tags and categories.

Eg. If keywords are color-coded differently for categories and tags, page identification in list layout would be a lot easier.

**Comment by willfaught** [comment]
Sorry for the delay in response. In v0.92.0, I added new paige-keyword-{categories,tags} CSS classes in v0.92.0 that are applied to the corresponding keywords. You should be able to use these to change the coloration or styling as needed. Please try it out.

**Comment by saurabh-sm** [comment]
Thanks for considering this request!

Can you let me know Which CSS file and property you're referring to? I'm assuming that the `keyword_style` would need to be `text`.

**Comment by willfaught** [comment]
It works for both keyword styles, either text or pills.

The HTML element for each keyword now has the CSS class paige-keyword-category or paige-keyword-tag applied to it in the class attribute. This means you can style them like this:

```toml
[params.paige]
style = """
.paige-keyword-category { color: red; }
.paige-keyword-tag { color: blue; }
"""
```

**Comment by saurabh-sm** [comment]
I've added 

```
[params.paige]
style = """
.paige-keyword-category { color: red; }
.paige-keyword-tag { color: blue; }
"""
```

to `hugo.toml`, but dont see changes in either layout.

**Comment by saurabh-sm** [comment]
I think in one of the previous releases (maybe 0.90), you had introduced configured Paige related parameters in the `hugo.toml`. I have `[params.paige]`, `[params.paige.list_page]`, and `[params.paige.page]` in `hugo.toml`.

The front matter of individual files has no Paige specific configuration - they have Hugo specific configuration like `title`, `description`, `date`, `authors`, `tags`, `categories`, and `weight`.

**Comment by willfaught** [comment]
@allocgator Sorry for the delay replying.

You can do something like this in hugo.toml:

```toml
[params.paige]
style = """
.paige-keyword-category { background-color: blue; }
.paige-keyword-tag { background-color: red; }
"""
```

to get an effect like this:

<img width="398" alt="Image" src="https://github.com/user-attachments/assets/15535fd1-030e-458f-a313-bf14d23fa534" />

and this:

<img width="802" alt="Image" src="https://github.com/user-attachments/assets/fd9dae7a-5b95-4fd3-96c8-6868db10f2f8" />

You can add whatever styling you want that way.

If you want to limit the style to sub-pages, you can do:

```toml
[params.paige]
style = """
#paige-pages .paige-keyword-category { background-color: blue; }
#paige-pages .paige-keyword-tag { background-color: red; }
"""
```

If you want to limit the style to non-sub-pages, you can do:

```toml
[params.paige]
style = """
#paige-metadata .paige-keyword-category { background-color: blue; }
#paige-metadata .paige-keyword-tag { background-color: red; }
"""
```

You should be seeing the described effect with the config you showed. Try copying the config I showed here and trying again. Does it still happen on the latest version of Hugo and Paige?

**Comment by allocgator** [comment]
Hi @willfaught, thanks for your response.

I tried it out and observed that it works when `keyword_style = "text"`, but not when `keyword_style = "pills"`. 

Having red and blue pills in the list layout (instead of grey) would look really cool :)

**Comment by willfaught** [comment]
@allocgator The default styling for the pills keywords is done with Bootstrap CSS classes, so you have to override their styles with your own styles using the `!important` keyword:

```css
.paige-keyword-category { background-color: blue !important; color: green !important; }
.paige-keyword-tag { background-color: red !important; color: green !important; }
```

<img width="443" alt="Image" src="https://github.com/user-attachments/assets/bbe4f6bd-228c-48a1-b14d-93807355bd4c" />
